nginx:
  image: nginx:latest
  ports:
    - "80:80"
    # - "443:443"
  volumes:
    - ./app:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
    # - ./nginx/ca:/etc/nginx/ca:ro
    - /etc/localtime:/etc/localtime:ro
  links:
    - php:__DOCKER_PHP_FPM__
    - php7:__DOCKER_PHP7_FPM__
php:
  build: ./php
  ports:
    - "9000:9000"
  volumes:
    - ./app:/usr/share/nginx/html
    - ./php/conf/php.ini:/etc/php/php.ini:rw
    - /etc/localtime:/etc/localtime:ro
  links:
    - mysql:mysql
mysql:
  build: ./mysql
  ports:
    - "127.0.0.1:3306:3306"
  volumes:
    - ./mysql/data:/var/lib/mysql:rw
    - ./mysql/sql:/tmp/sql:rw
    - ./mysql/etc:/etc/mysql:rw
    - /etc/localtime:/etc/localtime:ro
  environment:
    - MYSQL_ROOT_PASSWORD=123456
php7:
  build: ./php7
  ports:
    - "9001:9000"
  volumes:
    - ./app:/var/www
    - ./php7/etc:/usr/local/etc/php:rw
    - /etc/localtime:/etc/localtime:ro
  links:
    - mysql:mysql    
