nginx:
  image: nginx:latest
  ports:
    - "80:80"
    # - "443:443"
  volumes:
    - ./app:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
    # - ./nginx/ca:/etc/nginx/ca:ro
  links:
    - php:__DOCKER_PHP_FPM__
php:
  build: ./php-fpm
  ports:
    - "9000"
  volumes:
    - ./app:/usr/share/nginx/html
    - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:rw
  links:
    - mysql:mysql
mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  volumes:
    - ./mysql/data:/var/lib/mysql:rw
    - ./mysql/sql:/tmp/sql:rw
  environment:
    - MYSQL_ROOT_PASSWORD=123456