nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./app:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
    - ./nginx/ca:/etc/nginx/ca:ro
    - ./logs/nginx:/var/log/nginx:rw
  links:
    - php8:php8
    - php7:php7
mysql:
  build: ./mysql
  container_name: mysql
  volumes:
    - ./mysql/data:/var/lib/mysql:rw
    - ./mysql/sql:/tmp/sql:rw
    - ./mysql/etc:/etc/mysql:rw
  environment:
    - MYSQL_ROOT_PASSWORD=123456
php8:
  build: ./php8
  container_name: php8
  volumes:
    - ./app:/usr/share/nginx/html
    - ./php8/etc:/usr/local/etc/php:rw
    - ./php8/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw
    - ./logs/php8:/var/log/php:rw  
  links:
    - mysql:mysql
php7:
  build: ./php7
  container_name: php7
  volumes:
    - ./app:/usr/share/nginx/html
    - ./php7/etc:/usr/local/etc/php:rw
    - ./php7/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw
    - ./logs/php7:/var/log/php:rw  
  links:
    - mysql:mysql
