nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./app:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
    - ./nginx/ca:/etc/nginx/ca:ro
    - /etc/localtime:/etc/localtime:ro
    - ./logs/nginx:/var/log/nginx:rw
  links:
    - php:__DOCKER_PHP_FPM__
    - php7:__DOCKER_PHP7_FPM__  
php:
  build: ./php
  container_name: php
  ports:
    - "9000:9000"
  volumes:
    - ./app:/usr/share/nginx/html
    - ./php/etc:/usr/local/etc/php:rw
    - /etc/localtime:/etc/localtime:ro
  links:
    - mysql:mysql
mysql:
  build: ./mysql
  container_name: mysql
  ports:
    - "3308:3306"
  volumes:
    - ./mysql/data:/var/lib/mysql:rw
    - ./mysql/sql:/tmp/sql:rw
    - ./mysql/etc:/etc/mysql:rw
    - /etc/localtime:/etc/localtime:ro
  environment:
    - MYSQL_ROOT_PASSWORD=123456
php7:
  build: ./php7
  container_name: php7
  ports:
    - "9001:9000"
  volumes:
    - ./app:/usr/share/nginx/html
    - ./php7/etc:/usr/local/etc/php:rw
    - /etc/localtime:/etc/localtime:ro
    - ./php7/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw
    - ./logs/php7:/var/log/php:rw  
  links:
    - mysql:mysql
