######
# See: https://hub.docker.com/_/php/
######

#FROM php:7.0.5-fpm
FROM php7.2-fpm-alpine
MAINTAINER Young <zhy_0875@gmail.com>

######
# You can install php extensions using docker-php-ext-install
######

